# Generated by Django 3.1.2 on 2020-11-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_entry_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='description',
        ),
    ]
